Properly fix pipefail in playbooks
pipefail requires bash; we need to set bash as executable.

Signed-off-by: David Weinehall <david.weinehall@intel.com>

diff --git a/playbooks/vm_template_instantiate.yaml b/playbooks/vm_template_instantiate.yaml
--- a/playbooks/vm_template_instantiate.yaml
+++ b/playbooks/vm_template_instantiate.yaml
@@ -53,65 +53,78 @@
         dest: "{{ tempdir.path }}"
         mode: "0640"
     - name: "Create and start the cmt network"
-      ansible.builtin.shell: |
-        set -o pipefail
-        if ! $( virsh --connect qemu:///system net-list | grep cmt ); then
-            virsh --connect qemu:///system net-define {{ tempdir.path }}/net-cmt.xml
-            virsh --connect qemu:///system net-autostart cmt
-        fi
-        virsh --connect qemu:///system net-destroy cmt 2> /dev/null || /bin/true
-        virsh --connect qemu:///system net-start cmt
+      ansible.builtin.shell:
+        cmd: |
+          set -o pipefail
+          if ! $( virsh --connect qemu:///system net-list | grep cmt ); then
+              virsh --connect qemu:///system net-define {{ tempdir.path }}/net-cmt.xml
+              virsh --connect qemu:///system net-autostart cmt
+          fi
+          virsh --connect qemu:///system net-destroy cmt 2> /dev/null || /bin/true
+          virsh --connect qemu:///system net-start cmt
+        executable: "/bin/bash"
       changed_when: true
     - name: "Create DHCP entries for all instances"
-      ansible.builtin.shell: |
-        echo virsh --connect qemu:///system net-update cmt add ip-dhcp-host "<host mac='{{ item.2 }}' name='{{ item.0 }}' ip='{{ item.1 }}'/>" --live --config || /bin/true
-        virsh --connect qemu:///system net-update cmt add ip-dhcp-host "<host mac='{{ item.2 }}' name='{{ item.0 }}' ip='{{ item.1 }}'/>" --live --config || /bin/true
+      ansible.builtin.shell:
+        cmd: |
+          echo virsh --connect qemu:///system net-update cmt add ip-dhcp-host "<host mac='{{ item.2 }}' name='{{ item.0 }}' ip='{{ item.1 }}'/>" --live --config || /bin/true
+          virsh --connect qemu:///system net-update cmt add ip-dhcp-host "<host mac='{{ item.2 }}' name='{{ item.0 }}' ip='{{ item.1 }}'/>" --live --config || /bin/true
+        executable: "/bin/bash"
       loop: "{{ instances }}"
       changed_when: true
     - name: "Instantiate the VMs"
-      ansible.builtin.shell: |
-        echo virt-install --connect qemu:///system \
-            --cloud-init meta-data=/var/lib/libvirt/images/meta-data.{{ item.0 }},user-data=/var/lib/libvirt/images/user-data.{{ item.0 }} \
-            --virt-type kvm \
-            --name {{ item.0 }} \
-            --ram {{ vmram }} \
-            --vcpus={{ vcpus }} \
-            --os-variant {{ os_variant }} \
-            --disk path=/var/lib/libvirt/images/{{ item.0 }}.qcow2,format=qcow2 \
-            --import \
-            --network network=cmt,mac={{ item.2 }} \
-            --noautoconsole
-        virt-install --connect qemu:///system \
-            --cloud-init meta-data=/var/lib/libvirt/images/meta-data.{{ item.0 }},user-data=/var/lib/libvirt/images/user-data.{{ item.0 }} \
-            --virt-type kvm \
-            --name {{ item.0 }} \
-            --ram {{ vmram }} \
-            --vcpus={{ vcpus }} \
-            --os-variant {{ os_variant }} \
-            --disk path=/var/lib/libvirt/images/{{ item.0 }}.qcow2,format=qcow2 \
-            --import \
-            --network network=cmt,mac={{ item.2 }} \
-            --noautoconsole
+      ansible.builtin.shell:
+        cmd: |
+          set -o pipefail
+          echo virt-install --connect qemu:///system \
+              --cloud-init meta-data=/var/lib/libvirt/images/meta-data.{{ item.0 }},user-data=/var/lib/libvirt/images/user-data.{{ item.0 }} \
+              --virt-type kvm \
+              --name {{ item.0 }} \
+              --ram {{ vmram }} \
+              --vcpus={{ vcpus }} \
+              --os-variant {{ os_variant }} \
+              --disk path=/var/lib/libvirt/images/{{ item.0 }}.qcow2,format=qcow2 \
+              --import \
+              --network network=cmt,mac={{ item.2 }} \
+              --noautoconsole
+          virt-install --connect qemu:///system \
+              --cloud-init meta-data=/var/lib/libvirt/images/meta-data.{{ item.0 }},user-data=/var/lib/libvirt/images/user-data.{{ item.0 }} \
+              --virt-type kvm \
+              --name {{ item.0 }} \
+              --ram {{ vmram }} \
+              --vcpus={{ vcpus }} \
+              --os-variant {{ os_variant }} \
+              --disk path=/var/lib/libvirt/images/{{ item.0 }}.qcow2,format=qcow2 \
+              --import \
+              --network network=cmt,mac={{ item.2 }} \
+              --noautoconsole
+        executable: "/bin/bash"
       loop: "{{ instances }}"
       changed_when: true
     - name: "Create /etc/hosts entries for all instances"
-      ansible.builtin.shell: |
-        grep -q "{{ item.0 }}" /etc/hosts || printf -- "{{ item.1 }} {{item.0 }}  # VM instance created by CMT\n" >> /etc/hosts
+      ansible.builtin.shell:
+        cmd: |
+          set -o pipefail
+          grep -q "{{ item.0 }}" /etc/hosts || printf -- "{{ item.1 }} {{item.0 }}  # VM instance created by CMT\n" >> /etc/hosts
+        executable: "/bin/bash"
       loop: "{{ instances }}"
       become: true
       become_user: "root"
       changed_when: true
     - name: "Wait a reasonable time for the VMs to start"
-      ansible.builtin.shell: |
-        count=0
-        until timeout 0.2 ping -c 1 {{ item.0 }} > /dev/null; do
-            count=$(( count + 1 ))
-            if [ ${count} -gt 60 ]; then
-                printf -- "VMs failed to start within 60 seconds; giving up.\n"
-                exit 1
-            fi
-            sleep 1
-        done
-        sleep 1
+      ansible.builtin.shell:
+        cmd: |
+          set -o pipefail
+          count=0
+          until timeout 0.2 ping -c 1 {{ item.0 }} > /dev/null; do
+              count=$(( count + 1 ))
+              if [ ${count} -gt 60 ]; then
+                  printf -- "VMs failed to start within 60 seconds; giving up.\n"
+                  exit 1
+              fi
+              sleep 1
+          done
+          sleep 1
+        executable: "/bin/bash"
       loop: "{{ instances }}"
       changed_when: false
